[package]
name = "xpd_timer"
version = "0.1.0"
authors = ["Huayao.Wang <wanghuayao@hotmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"

[dev-dependencies]
rand = "0.8.5"